#!/bin/bash

# Copyright (c) 2018 Joe Schillinger <me@schil.li>
  # (For the creation of the original ufetch).

# Copyright (c) 2026 João Vitor Duarte <sakaki@tuta.io>
  # (Due to subsequent modifications based on Joe Schillinger's work).

UFETCH_PLUS_VERSION="2.0"

if [[ $EUID == 0 ]]; then
    USER_EUID="$(printf "(\033[1;91m$EUID\033[0m)")"
else
    USER_EUID="$(printf "(\033[1m$EUID\033[0m)")"
fi

USERNAME="$(basename $HOME)"
. /etc/os-release ; OS="$NAME"
KERNEL="$(awk '{ print $1, $3 }' /proc/version)"
UPTIME="$(uptime | awk '{ printf $3 }' | tr -d ',')"
SHELL_I="$(basename $SHELL)"
RAM="$(awk 'NR==1 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)"
FREE_RAM="$(($RAM-$(awk 'NR==3 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)))"
SWAP="$(awk 'NR==15 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)"
FREE_SWAP="$(($SWAP-$(awk 'NR==16 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)))"
CPU="$(awk -F': ' '/model name/ { print $2 ; exit }' /proc/cpuinfo)"
CPU_CORES="($(awk -F': ' '/cpu cores/ { print $2 ; exit }' /proc/cpuinfo))"

BOLD="$(printf "\033[1m")"
BLACK="$(printf "\033[30m")"
RED="$(printf "\033[31m")"
GREEN="$(printf "\033[32m")"
YELLOW="$(printf "\033[33m")"
BLUE="$(printf "\033[34m")"
MAGENTA="$(printf "\033[35m")"
CYAN="$(printf "\033[36m")"
WHITE="$(printf "\033[37m")"
RESET="$(printf "\033[0m")"
UNDERLINE="$(printf "\033[4m")"
INFO="${RESET}${BOLD}${WHITE}"

#OS="Linux"
#OS="Alpine Linux"
#OS="Debian"

if [[ $OS == "Alpine Linux" ]]; then
    COLOR_0=${RESET}${BOLD}$BLUE ; COLOR_1=${RESET}$WHITE
    PACKAGES="$(apk info | wc -l)"
    LINE1="${COLOR_0}     /\ /\         "
    LINE2="${COLOR_0}    /${COLOR_1}/ ${COLOR_0}\  \       "
    LINE3="${COLOR_0}   /${COLOR_1}/   ${COLOR_0}\  \      "
    LINE4="${COLOR_0}  /${COLOR_1}//    ${COLOR_0}\  \     "
    LINE5="${COLOR_0}  ${COLOR_1}//      ${COLOR_0}\  \\    "
    LINE6="${COLOR_0}           \  \   "
    LINE7="${COLOR_0}            \     "
    LINE8="${COLOR_0}                  "
    LINE9="${COLOR_0}                  "
elif [[ $OS == "Arch Linux" ]]; then
    COLOR_0=${RESET}${BOLD}${CYAN} ; COLOR_1=${RESET}${CYAN}
    PACKAGES="$(pacman -Q | wc -l)"
    LINE1="${COLOR_0}        /\          "
    LINE2="${COLOR_0}       /^^\        "
    LINE3="${COLOR_0}      /\   \       "
    LINE4="${COLOR_0}     /  ${COLOR_1}__  \      ${COLOR_0}"
    LINE5="${COLOR_1}    /  (  )  \     ${COLOR_0}"
    LINE6="${COLOR_1}   / __|  |__\\\\    ${COLOR_0}"
    LINE7="${COLOR_1}  ///        \\\\\   ${COLOR_0}"
    LINE8="${COLOR_0}                   "
    LINE9="${COLOR_0}                   "
elif [[ $OS == "Debian" ]]; then
    COLOR_0=${RESET}${BOLD}${RED} ; COLOR_1=${RESET}${RED}
    PACKAGES="$(dpkg -l | wc -l)"
    LINE1="${COLOR_0}    _____     ${COLOR_0}"
    LINE2="${COLOR_0}   /  __ \\   ${COLOR_0}"
    LINE3="${COLOR_0}  |  /    |  ${COLOR_0}"
    LINE4="${COLOR_0}  |  ${COLOR_1}\\___-   ${COLOR_0}"
    LINE5="${COLOR_1}  -_         ${COLOR_0}"
    LINE6="${COLOR_1}    --_      ${COLOR_0}"
    LINE7="${COLOR_0}             ${COLOR_0}"
    LINE8="${COLOR_0}             ${COLOR_0}"
    LINE9="${COLOR_0}             ${COLOR_0}"
else
    COLOR_0=${RESET}${BOLD}${WHITE} ; COLOR_1=${RESET}${WHITE} ; COLOR_2=${RESET}${YELLOW}
    PACKAGES="unknown"
    LINE1="${COLOR_0}      ___       ${COLOR_0}"
    LINE2="${COLOR_0}     (${COLOR_1}.. ${COLOR_0}\     ${COLOR_0}"
    LINE3="${COLOR_0}     (${COLOR_2}<> ${COLOR_0}|     ${COLOR_0}"
    LINE4="${COLOR_0}    /${COLOR_1}/  \\ ${COLOR_0}\\    ${COLOR_0}"
    LINE5="${COLOR_0}   ( ${COLOR_1}|  | ${COLOR_0}/|   ${COLOR_0}"
    LINE6="${COLOR_2}  _${COLOR_0}/\\ ${COLOR_1}__)${COLOR_0}/${COLOR_2}_${COLOR_0})   ${COLOR_0}"
    LINE7="${COLOR_2}  \/${COLOR_0}-____${COLOR_2}\/${RESET}    ${COLOR_0}"
    LINE8="${COLOR_0}               ${COLOR_0}"
    LINE9="${COLOR_0}               ${COLOR_0}"
fi

cat <<EOF
                     
${LINE1}${UNDERLINE}${USERNAME}@${HOSTNAME}${RESET}${USER_EUID}
${LINE2} OS:        ${INFO}${OS}${RESET}
${LINE3} KERNEL:    ${INFO}${KERNEL}${RESET}
${LINE4} UPTIME:    ${INFO}${UPTIME}${RESET}
${LINE5} PACKAGES:  ${INFO}${PACKAGES}${RESET}
${LINE6} SHELL:     ${INFO}${SHELL_I}${RESET}
${LINE7} CPU:       ${INFO}${CPU} ${CPU_CORES}${RESET}
${LINE8} RAM:       ${INFO}${FREE_RAM} MiB / ${RAM} MiB${RESET} 
${LINE9} SWAP:      ${INFO}${FREE_SWAP} MiB / ${SWAP} MiB${RESET}

EOF
