#!/bin/bash

# Copyright (c) 2018 Joe Schillinger <me@schil.li>
  # (For the creation of the original ufetch).

# Copyright (c) 2026 João Vitor Duarte <sakaki@tuta.io>
  # (Due to subsequent modifications based on Joe Schillinger's work).

USERNAME="$(basename $HOME)" ; HOSTNAME="$(cat /etc/hostname)"
OS="$(grep ^NAME= /etc/os-release | sed 's/NAME=//' | tr -d '"')"
KERNEL="$(awk '{ print $1, $3 }' /proc/version)"
UPTIME_H="$(uptime -p | awk '{ print $2 }')"
UPTIME_M="$(uptime -p | awk '{ print $4 }')"
PACKAGES="$(pacman -Q | wc -l)"
SHELL_I="$(basename $SHELL)"
LOCALE="$(printf $LANG)"
RAM="$(($(cat /proc/meminfo | grep ^MemTotal: | sed 's/MemTotal: *//' | sed 's/kB//')/1024))"
FREE_RAM="$(($RAM-$(cat /proc/meminfo | grep ^MemAvailable: | sed 's/MemAvailable: *//' | sed 's/kB//')/1024))"
SWAP="$(($(cat /proc/meminfo | grep ^SwapTotal: | sed 's/SwapTotal: *//' | sed 's/kB//')/1024))"
SWAP_FREE="$(($SWAP-$(cat /proc/meminfo | grep ^SwapFree: | sed 's/SwapFree: *//' | sed 's/kB//')/1024))"


if [[ $EUID == 0 ]]; then
    USER_EUID="$(printf "(\033[1;91m$EUID\033[0m)")"
else
    USER_EUID="$(printf "(\033[1m$EUID\033[0m)")"
fi

CPU_BRUTE="$(grep ^model\ name /proc/cpuinfo | awk '{ print $4, $5 }' | head -n 1)"
CPU_CORES="$(grep ^cpu\ cores /proc/cpuinfo | awk '{ print $4 }' | head -n 1)"
if [[ $CPU_BRUTE == "Intel(R) Core(TM)" ]]; then
    CPU="$(grep ^model\ name /proc/cpuinfo | awk '{ print $6, $8, $9}' | head -n 1) ($CPU_CORES)"
fi

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		ENVTYPE='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		ENVTYPE='DE'
		WM="${DESKTOP_SESSION}"
	else
		ENVTYPE='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	ENVTYPE='WM'
fi

BOLD="$(printf "\033[1m")"
BLACK="$(printf "\033[30m")"
RED="$(printf "\033[31m")"
GREEN="$(printf "\033[32m")"
YELLOW="$(printf "\033[33m")"
BLUE="$(printf "\033[34m")"
MAGENTA="$(printf "\033[35m")"
CYAN="$(printf "\033[36m")"
WHITE="$(printf "\033[37m")"
RESET="$(printf "\033[0m")"
UNDERLINE="$(printf "\033[4m")"

LABELS="${RESET}${BOLD}${CYAN}"
USER_N_HOST="${RESET}${BOLD}${CYAN}"
INFO="${RESET}${BOLD}${WHITE}"
COLOR_0="${RESET}${BOLD}${CYAN}"
COLOR_1="${RESET}${CYAN}"

cat <<EOF
                     
${COLOR_0}         .           ${LABELS}${UNDERLINE}${USERNAME}@${HOSTNAME}${RESET}${USER_EUID}
${COLOR_0}        / \\          ${LABELS}OS:${INFO}        ${OS}${RESET}
${COLOR_0}       /   \\         ${LABELS}KERNEL:${INFO}    ${KERNEL}${RESET}
${COLOR_0}      /^.   \\        ${LABELS}UPTIME:${INFO}    ${UPTIME_H}:${UPTIME_M}${RESET}
${COLOR_0}     /  .-.  \\       ${LABELS}PACKAGES:${INFO}  ${PACKAGES}${RESET}
${COLOR_0}    /  (   ) _\\      ${LABELS}SHELL:${INFO}     ${SHELL_I}${RESET}
${COLOR_0}   / _.~   ~._^\\     ${LABELS}${ENVTYPE}:${INFO}        ${WM}${RESET}
${COLOR_0}  /.^         ^.\\    ${COLOR_0}LOCALE:${INFO}    ${LOCALE}${RESET}
                     ${COLOR_0}CPU:${INFO}       ${CPU}${RESET}
                     ${COLOR_0}RAM:${INFO}       ${FREE_RAM} MiB / ${RAM} MiB${RESET}
                     ${COLOR_0}SWAP:${INFO}      ${SWAP_FREE} MiB / ${SWAP} MiB${RESET} 

EOF
